### ISSUE TITLE
Handling invalid login credentials / accounts that do not exist.

### ISSUE THREAD

**Issue by asenawritescode** [pdovhomilja/nextcrm-app#21]
I get an error message when I try to login with a non-exiting account.

> Current behaviour :
> ![image](https://github.com/pdovhomilja/nextcrm-app/assets/67445192/ae44d6c6-e431-462c-ae1a-e38bb1d0c802)

> Expected Behaviour :
> Toast notifying "User email/password is incorrect" and also when performing actions

> [Shadcn Toast component](https://ui.shadcn.com/docs/components/toast)
> ![image](https://github.com/pdovhomilja/nextcrm-app/assets/67445192/116c6a32-00b0-4071-8cca-05976d138b48)

> Reference [Usability Heuristics](https://www.nngroup.com/articles/ten-usability-heuristics/) look at rule `#9`

**Comment by asenawritescode** [comment]
Let me know if I can contribute to the project.

**Comment by pdovhomilja** [comment]
Hi, of course you can. Thank you for the first issue in repo :-D

**Comment by pdovhomilja** [comment]
After a quick view of the problem, I forgot to set redirect to false in the auth callback. Now it is fixed.
