### ISSUE TITLE
[BUG - DEMO:]Google Authentification blocked

### ISSUE THREAD

**Issue by Senooy** [pdovhomilja/nextcrm-app#25]
### Describe the bug

I would like to report a problem encountered while using the demo version of NextCRM. The issue is specifically related to the Google authentication process.

### Steps to reproduce

Navigate to the CRM demo site.
Click on the option to sign in using Google authentication.
Log In
Google Auth message : Access blocked

### Browsers

Chrome

**Comment by pdovhomilja** [comment]
Hi Senooy, thanks for this issue. The problem was in the OAuth. I fixed it.
