### ISSUE TITLE
[BUG:]  Login SignUp page Component

### ISSUE THREAD

**Issue by Ankit7m16** [pdovhomilja/nextcrm-app#34]
### Describe the bug

Login SignUp page Component is not Proper onScroll it is showing a Scrollbar in right side
<img width="1096" alt="image" src="https://github.com/pdovhomilja/nextcrm-app/assets/168418072/82bb0fa9-3ade-4acd-8092-bff77f35c59b">

### Steps to reproduce

Ho

**Comment by Ankit7rma** [comment]
MacOS

**Comment by pdovhomilja** [comment]
![Snímek obrazovky 2024-07-05 v 10 50 44](https://github.com/pdovhomilja/nextcrm-app/assets/41537049/1638cc98-0a9c-4e59-b7ff-47291ddbdef7)

**Comment by Ankit7rma** [comment]
Uploading Screen Recording 2024-07-05 at 2.23.57 PM.mov…
