### ISSUE TITLE
It is not possible to create new account

### ISSUE THREAD

**Issue by skoruba** [pdovhomilja/nextcrm-app#4]
Hi @pdovhomilja 

This project looks nice - I am trying to test your app on [demo.nextcrm.io](https://demo.nextcrm.io/) - but I cannot create new account.

Please take a look at this screenshot:

![image](https://github.com/pdovhomilja/nextcrm-app/assets/35664089/902443cd-212e-42f5-92c3-0fb41f05720e)

Thanks

Jan

**Comment by pdovhomilja** [comment]
Hi Jan, I just fixed it. Thank you for your feedback. There is a build process on Vercel in approx 15 minutes, there will be a fixed version ready.
